SERVICES = {
    "heroku": {
        "name": "Heroku",
        "fingerprint": "No such app",
        "cname_examples": ["your-app.herokuapp.com", "your-app.herokudns.com"],
        "description": "Heroku is a cloud platform used to deploy and run web applications. Developers frequently use Heroku for staging environments, side projects, and prototypes — then delete the app without removing the DNS record.",
        "why_vulnerable": "When a Heroku app is deleted, the subdomain pointing to it becomes claimable. Anyone can create a new Heroku app at the same address and immediately control what appears at your subdomain. Heroku's 'No such app' error page is one of the most recognizable takeover signals in bug bounty hunting.",
        "how_to_fix": "Delete the CNAME record pointing to herokuapp.com from your DNS settings. If you still need the subdomain, create a new Heroku app and reconfigure it properly.",
        "test_subdomain": "staging.example.com",
    },
    "github-pages": {
        "name": "GitHub Pages",
        "fingerprint": "There isn't a GitHub Pages site here",
        "cname_examples": ["username.github.io", "orgname.github.io"],
        "description": "GitHub Pages is a free static site hosting service. Developers commonly point subdomains like docs.example.com or blog.example.com to GitHub Pages sites, then delete the repository or disable Pages without cleaning up DNS.",
        "why_vulnerable": "When a GitHub Pages site is deleted or disabled, the CNAME target becomes unclaimed. Anyone can create a GitHub Pages site at that address and serve content under your subdomain. The classic fingerprint 'There isn't a GitHub Pages site here' confirms the takeover is possible.",
        "how_to_fix": "Remove the CNAME record from your DNS settings, or re-enable GitHub Pages on the original repository.",
        "test_subdomain": "docs.example.com",
    },
    "aws-s3": {
        "name": "AWS S3",
        "fingerprint": "NoSuchBucket",
        "cname_examples": ["your-bucket.s3-website-us-east-1.amazonaws.com", "your-bucket.s3.amazonaws.com"],
        "description": "AWS S3 buckets configured for static website hosting are a common target. Companies use S3 to host static assets, documentation, or landing pages, then delete the bucket while the DNS record remains.",
        "why_vulnerable": "S3 bucket names are globally unique but claimable by anyone. When a bucket is deleted, an attacker can create a new bucket with the same name in the same region and immediately control the subdomain. This is particularly dangerous because S3 can serve arbitrary HTML, JavaScript, and files.",
        "how_to_fix": "Remove the CNAME record from your DNS settings. If you need the subdomain, recreate the S3 bucket with the same name and reconfigure it.",
        "test_subdomain": "assets.example.com",
    },
    "vercel": {
        "name": "Vercel",
        "fingerprint": "The deployment could not be found",
        "cname_examples": ["cname.vercel-dns.com"],
        "description": "Vercel is a popular deployment platform for frontend frameworks like Next.js, React, and Vue. Projects get spun up and deleted constantly, and custom domain configurations are often left behind.",
        "why_vulnerable": "When a Vercel project is deleted or a custom domain is removed without updating DNS, the subdomain dangles. The fingerprint 'The deployment could not be found' confirms the project no longer exists at that address.",
        "how_to_fix": "Remove the CNAME record pointing to vercel-dns.com from your DNS settings.",
        "test_subdomain": "app.example.com",
    },
    "netlify": {
        "name": "Netlify",
        "fingerprint": "Not Found - Request ID",
        "cname_examples": ["your-site.netlify.app"],
        "description": "Netlify is widely used for deploying marketing sites, landing pages, and JAMstack applications. Campaign microsites and A/B test variants frequently get deleted without DNS cleanup.",
        "why_vulnerable": "Deleted Netlify sites leave dangling CNAMEs that are claimable. The 'Not Found - Request ID' response confirms the site no longer exists and the subdomain is vulnerable.",
        "how_to_fix": "Remove the CNAME record pointing to netlify.app from your DNS settings.",
        "test_subdomain": "landing.example.com",
    },
    "azure": {
        "name": "Microsoft Azure",
        "fingerprint": "404 Web Site not found",
        "cname_examples": ["your-app.azurewebsites.net", "your-app.azurefd.net", "your-app.azureedge.net"],
        "description": "Azure has multiple services vulnerable to subdomain takeover — App Service, Front Door, CDN, and Traffic Manager. Enterprise companies running on Azure often have dozens of subdomains pointing to Azure resources.",
        "why_vulnerable": "When Azure resources are decommissioned without DNS cleanup, the subdomains become claimable. Azure is particularly risky because enterprise teams often don't have a centralized view of all their DNS records.",
        "how_to_fix": "Remove the CNAME record from your DNS settings. For Azure-specific guidance, check that all Azure resource DNS configurations are cleaned up when resources are deleted.",
        "test_subdomain": "portal.example.com",
    },
    "shopify": {
        "name": "Shopify",
        "fingerprint": "Sorry, this shop is currently unavailable",
        "cname_examples": ["your-store.myshopify.com"],
        "description": "E-commerce businesses frequently set up custom subdomains for their Shopify stores — shop.example.com or store.example.com. When they migrate to a different platform or shut down the store, the CNAME often stays.",
        "why_vulnerable": "A closed or deleted Shopify store leaves the subdomain claimable. An attacker can create a new Shopify store at that address and serve a fake shop under your brand — a serious phishing risk for your customers.",
        "how_to_fix": "Remove the CNAME record pointing to myshopify.com from your DNS settings.",
        "test_subdomain": "shop.example.com",
    },
    "zendesk": {
        "name": "Zendesk",
        "fingerprint": "Help Center Closed",
        "cname_examples": ["your-company.zendesk.com"],
        "description": "Support portals are a goldmine for subdomain takeovers. Companies set up help.example.com or support.example.com pointing to Zendesk, then migrate to a different support platform without cleaning up DNS.",
        "why_vulnerable": "A takeover of a support subdomain is particularly dangerous. Users who trust help.example.com might enter credentials, describe sensitive issues, or share personal information — all going to an attacker.",
        "how_to_fix": "Remove the CNAME record pointing to zendesk.com from your DNS settings.",
        "test_subdomain": "help.example.com",
    },
    "ghost": {
        "name": "Ghost",
        "fingerprint": "Domain not configured",
        "cname_examples": ["your-blog.ghost.io"],
        "description": "Ghost is a popular blogging and newsletter platform. blog.example.com or news.example.com pointing to Ghost is extremely common, and when companies rebrand or migrate their blog, the DNS record is often forgotten.",
        "why_vulnerable": "An unconfigured Ghost domain returns 'Domain not configured', confirming the subdomain is claimable. An attacker can set up a Ghost blog at that address and publish content under your brand.",
        "how_to_fix": "Remove the CNAME record pointing to ghost.io from your DNS settings.",
        "test_subdomain": "blog.example.com",
    },
    "fastly": {
        "name": "Fastly",
        "fingerprint": "Fastly error: unknown domain",
        "cname_examples": ["your-domain.global.ssl.fastly.net"],
        "description": "Fastly is a CDN used by high-traffic websites to serve content quickly. When a Fastly service configuration is removed without DNS cleanup, the subdomain becomes vulnerable.",
        "why_vulnerable": "CDN takeovers are high impact. A takeover of a Fastly-backed subdomain means an attacker can serve content — including malicious scripts — to users who expect to be on your site.",
        "how_to_fix": "Remove the CNAME record pointing to fastly.net from your DNS settings.",
        "test_subdomain": "cdn.example.com",
    },
    "webflow": {
        "name": "Webflow",
        "fingerprint": "The page you are looking for doesn't exist",
        "cname_examples": ["proxy.webflow.com"],
        "description": "Webflow is a no-code website builder popular for marketing sites and landing pages. When a Webflow project is deleted or unpublished without removing the custom domain DNS record, the subdomain dangles.",
        "why_vulnerable": "An unpublished or deleted Webflow site leaves the subdomain claimable. Anyone can create a Webflow site and point it to that address.",
        "how_to_fix": "Remove the CNAME record pointing to proxy.webflow.com from your DNS settings.",
        "test_subdomain": "www.example.com",
    },
    "netlify-app": {
        "name": "Netlify",
        "fingerprint": "Not Found - Request ID",
        "cname_examples": ["your-site.netlify.app"],
        "description": "Netlify is widely used for deploying marketing sites, landing pages, and JAMstack applications.",
        "why_vulnerable": "Deleted Netlify sites leave dangling CNAMEs that are claimable by anyone.",
        "how_to_fix": "Remove the CNAME record pointing to netlify.app from your DNS settings.",
        "test_subdomain": "landing.example.com",
    },
    "surge": {
        "name": "Surge.sh",
        "fingerprint": "project not found",
        "cname_examples": ["your-project.surge.sh"],
        "description": "Surge is a simple static site hosting platform popular with developers for quickly deploying projects. Sites are easy to create and easy to forget about.",
        "why_vulnerable": "When a Surge project is deleted, the subdomain pointing to it becomes claimable. The 'project not found' fingerprint confirms the takeover is possible.",
        "how_to_fix": "Remove the CNAME record pointing to surge.sh from your DNS settings.",
        "test_subdomain": "project.example.com",
    },
    "hubspot": {
        "name": "HubSpot",
        "fingerprint": "This page isn't available",
        "cname_examples": ["your-domain.hs-sites.com", "your-domain.hubspotpagebuilder.com"],
        "description": "HubSpot is a marketing and CRM platform. Companies frequently set up landing pages and campaign microsites on HubSpot subdomains, then migrate away without cleaning DNS.",
        "why_vulnerable": "Deleted HubSpot pages leave dangling CNAME records. An attacker can create a HubSpot page at that address and serve phishing content under your brand.",
        "how_to_fix": "Remove the CNAME record pointing to hs-sites.com or hubspotpagebuilder.com from your DNS settings.",
        "test_subdomain": "landing.example.com",
    },
    "readme": {
        "name": "Readme.io",
        "fingerprint": "Project doesnt exist... yet!",
        "cname_examples": ["your-docs.readme.io"],
        "description": "Readme.io is a documentation platform used by SaaS companies to host their API docs. docs.example.com or developers.example.com pointing to Readme is very common.",
        "why_vulnerable": "When a Readme project is deleted, the subdomain becomes claimable. An attacker serving fake API documentation under your brand could mislead developers integrating with your product.",
        "how_to_fix": "Remove the CNAME record pointing to readme.io from your DNS settings.",
        "test_subdomain": "docs.example.com",
    },
}